#include<stdio.h>
#include<fcntl.h> //for fd open
#include<unistd.h> //for execl
#include<string.h>
#include<stdlib.h>
#include <sys/wait.h>

int main(){
	pid_t pid=fork();
	if(pid<0){
		perror("fork faild");
		exit(0);
	}

	if(pid == 0){
		// -------- CHILD PROCESS ----------
        printf("Child: Creating file using system calls...\n");

	int fd =open("genprog.c",O_CREAT | O_WRONLY,0644);

	if(fd < 0){
		perror("open failed");
		exit(1);
	}

	char *code =
	"/* Generated by Child */\n"
	"#include <stdio.h>\n"
	"int main() {\n"
	"    printf(\"Hello from generated C file!\\n\");\n"
	"    return 0;\n"
	"}\n";


	write(fd,code,strlen(code));
	close(fd);
	printf("child file genprog.c written and cloe.\n");
	exit(0);
	}
	else{
		wait(NULL);
		printf("parent: cild finished,now i am read that\n");

		int fd = open("genprog.c",O_RDONLY);
		if (fd < 0) {
          		  perror("open read failed");
            		  exit(1);
		}
		char buffer[120];
		int r;
		printf("n==== File Content Start ====\n");
		r=read(fd,buffer,sizeof(buffer)-1);
	//	while((r=read(fd,buffer,sizeof(buffer)-1))>0);{
		while(r>0){
			buffer[r]='\0';
			printf("%s",buffer);
		}
	 printf("\n==== File Content End ====\n");
	 close(fd);

	 // ---- COMPILE THE GENERATED FILE ----
        printf("Parent: Compiling generated file...\n");
	
	pid_t pid2 = fork();

	if(pid2==0){
		execlp("gcc","gcc","genprog.c","-o","out",NULL);
		perror("exec compile failed");
		exit(1);
	}else{
		wait(NULL);
		printf("parent: copliation done \n");
	  printf("Parent: Executing generated program using exec...\n");
	  execl("./out","./out",NULL);
	  perror("exec run failed");
	  exit(1);
	}
	}
	return 0;
}

			
	
